version: '3'

networks:
  default:
    driver: nat

services:
  identityserver:
    image: identityserver
    build:
      context: ./Identityserver
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
     - default

  movieswebapp:
    image: movieswebapp
    build:
      context: ./MoviesWebApp
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
    networks:
     - default