version: "3.1"

networks:
  default:
    driver: bridge

services:
  identityserver:
    image: identityserver
    build:
      context: ./Identityserver
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
     - default

  movieswebapp:
    image: movieswebapp
    build:
      context: ./MoviesWebApp
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"
    networks:
     - default

  singlepageapp:
    image: singlepageapp
    build:
      context: ./SPA
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8082
    ports:
      - "8082:8082"
    networks:
     - default 

  productapi:
    image: productapi
    build:
      context: ./ProductAPI
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8083
    ports:
      - "8083:8083"
    networks:
     - default     
  
  shibboleth:
    build: ./Shibboleth/
    depends_on: 
      - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    ports:
     - "8090:8080"
    networks:
     - default
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer     
   
  ldap:
    build: ./ldap/
    networks:
     - default
    ports:
      - "389:389"

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  ssp_key:
    file: ./secrets/simplesamlphp/server.pem
  sp_key:
    file: ./secrets/sp/sp-key.pem
